import assert from "node:assert/strict";
import test from "node:test";
import { TerminalSplitCompositor } from "../src/fixed-editor/terminal-split.ts";

// Terminal.rows must be a getter defined on the prototype (not an own data
// property) so it behaves like the real terminal object the compositor is
// designed for: `install()` shadows it with an own-property getter, while
// `readRows()` keeps a reference to this original accessor to read the raw
// (unshadowed) row count without recursing into the compositor's override.
class FakeTerminal {
  columns = 80;
  private _rows = 24;
  get rows() {
    return this._rows;
  }
  set rows(value: number) {
    this._rows = value;
  }
  write(_data: string): void {}
}

function makeTui(transcriptLines: string[]) {
  let fullRenderCalls = 0;
  const terminal = new FakeTerminal();
  const tui: any = {
    children: [],
    terminal,
    render(_width: number) {
      fullRenderCalls++;
      return transcriptLines;
    },
    doRender() {},
    requestRender() {},
  };
  return { tui, terminal, getFullRenderCalls: () => fullRenderCalls };
}

function scrollWheelUp(): string {
  // SGR mouse sequence, base button 64 = wheel up.
  return "\x1b[<64;10;5M";
}

test("scrolling a long transcript does not re-render the full underlying content per scroll tick", () => {
  const transcript = Array.from({ length: 5000 }, (_, i) => `line ${i}`);
  const { tui, terminal, getFullRenderCalls } = makeTui(transcript);

  const compositor = new TerminalSplitCompositor({
    tui,
    terminal,
    renderCluster: () => ({ lines: ["editor"], cursor: null }),
  });

  compositor.install();

  // Simulate one real render pass (equivalent to pi's own doRender pipeline
  // calling tui.render once) so the compositor caches the full transcript.
  tui.render(terminal.columns);
  assert.equal(getFullRenderCalls(), 1, "expected exactly one full-transcript render after the initial pass");

  const initialScrollOffset = (compositor as any).scrollOffset as number;

  // Simulate a burst of scroll-wheel input, as generated by a fast trackpad
  // flick over a long conversation.
  for (let i = 0; i < 200; i++) {
    (compositor as any).handleInput(scrollWheelUp());
  }

  assert.equal(
    getFullRenderCalls(),
    1,
    "scrolling must not trigger additional full-transcript renders; it should reuse the cached lines",
  );

  const scrolledOffset = (compositor as any).scrollOffset as number;
  assert.ok(scrolledOffset > initialScrollOffset, "scroll offset should still advance while scrolling");

  compositor.dispose();
});

test("clicking/selecting in the transcript also reuses cached lines instead of re-rendering", () => {
  const transcript = Array.from({ length: 3000 }, (_, i) => `line ${i}`);
  const { tui, terminal, getFullRenderCalls } = makeTui(transcript);

  const compositor = new TerminalSplitCompositor({
    tui,
    terminal,
    renderCluster: () => ({ lines: ["editor"], cursor: null }),
  });

  compositor.install();
  tui.render(terminal.columns);
  assert.equal(getFullRenderCalls(), 1);

  // Left mouse press (button 0) at column 10, row 5.
  (compositor as any).handleInput("\x1b[<0;10;5M");
  // Release.
  (compositor as any).handleInput("\x1b[<0;10;5m");

  assert.equal(
    getFullRenderCalls(),
    1,
    "click handling must not re-render the full transcript just to resync viewport bookkeeping",
  );

  compositor.dispose();
});
